[versions]
compose = "1.2.0"
compose-compiler = "1.2.0"

[libraries]
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version = "1.8.0" }

# compose
androidx-compose-ui = { module = "androidx.compose.ui:ui" , version.ref="compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref="compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref="compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref="compose" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref="compose" }
androidx-compose-material-material = { module = "androidx.compose.material:material", version.ref="compose" }
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version = "1.5.1" }
# end compose libs

# lifecycle
androidx-lifecycle-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.5.1" }
#end lifecycle

# junit
junit-junit = { module = "junit:junit", version = "4.13.2" }
androidx-test-junit-ext = { module = "androidx.test.ext:junit", version = "1.1.3" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }

#end testing

[bundles]

[plugins]